version: "3"

services:
  # Front end of application, written in python
  vote:
    image: "dockersamples/examplevotingapp_vote:before"
    ports:
      - 5000:80

  # In-memory ket/value storage for incoming votes
  redis:
    image: "redis:3.2"

  # Used to fetch votes from Redis and store in a Postgres db
  worker:
    image: "dockersamples/examplevotingapp_worker"

  # Database, points to /var/lib/postgresql/data to persist data
  db:
    image: "postgres:9.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  # Node web app that shows results to administrators
  result:
    image: "dockersamples/examplevotingapp_result:before"
    ports:
      - 5001:80
